services:
  - type: web
    name: Raffley # Replace
    env: elixir
    repo: https://github.com/prashsamosa/Raffle.git # Replace
    branch: main # Or your branch
    buildCommand: mix deps.get && mix phx.digest --all && mix release
    startCommand: _build/prod/rel/Raffley/bin/Raffley start # Replace
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY_BASE
        value: ${SECRET_KEY_BASE}
      - key: POOL_SIZE
        value: 15 # Adjust
      # Add other env vars if needed