services:
  - type: web
    name: Raffley-app # You can choose a different name for your Render app
    env: elixir
    repo: https://github.com/prashsamosa/Raffley
    branch: main # Or your deployment branch (check your repository)
    buildCommand: mix deps.get && mix phx.digest --all && mix release
    startCommand: _build/prod/rel/Raffley/bin/Raffley start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY_BASE
        value: ${SECRET_KEY_BASE}
      - key: POOL_SIZE
        value: 15 # Adjust as needed
      # Add other environment variables your app needs