services:
  - type: web
    name: raffley
    env: elixir
    repo: https://github.com/prashsamosa/Raffley
    branch: main
    buildCommand: mix deps.get && mix phx.digest --all && mix release
    startCommand: |
      echo "Current working directory:"
      pwd
      echo "Listing _build/prod/rel/raffley/bin/:"
      ls -l _build/prod/rel/raffley/bin/
      echo "Attempting to start the application..."
      _build/prod/rel/raffley/bin/raffley start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY_BASE
        value: ${SECRET_KEY_BASE}
      - key: POOL_SIZE
        value: 15